import { describe, expect, it } from "vitest";

import { parseAnswerSections } from "./sectionParser";

describe("parseAnswerSections", () => {
  it("parses inline Chinese diagnostic labels into stable sections", () => {
    const sections = parseAnswerSections([
      "根因：目前更像是外部依赖链路异常。",
      "",
      "证据：",
      "- 已观测：aiops-host-agent 状态 ok",
      "- 已观测：external:18090 状态 unknown",
      "",
      "下一步：继续确认 external:18090 对应服务。",
    ].join("\n"));

    expect(sections.map((section) => section.kind)).toEqual([
      "root_cause",
      "evidence",
      "next_steps",
    ]);
    expect(sections[0].markdown).toContain("目前更像是外部依赖链路异常");
    expect(sections[1].markdown).toContain("external:18090");
  });

  it("parses bold labels generated by MessageMarkdown normalization", () => {
    const sections = parseAnswerSections([
      "**根因：** aiops-host-agent 的外部依赖异常。",
      "",
      "**证据：**",
      "- Coroot RCA 查询成功",
    ].join("\n"));

    expect(sections.map((section) => section.kind)).toEqual([
      "root_cause",
      "evidence",
    ]);
  });

  it("falls back to a single unknown section when no diagnostic label exists", () => {
    const sections = parseAnswerSections("当前服务状态需要继续观察。");

    expect(sections).toEqual([
      expect.objectContaining({
        kind: "unknown",
        markdown: "当前服务状态需要继续观察。",
      }),
    ]);
  });
});
