#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

forbidden='AIOPS_RUNNER_DISABLED|AIOPS_RUNNER_STUDIO_UPSTREAM_URL|RUNNER_STUDIO_UPSTREAM_URL|AIOPS_RUNNER_API_BASE_URL|AIOPS_BOOTSTRAP_LLM_CONFIG|AIOPS_LLM_PROVIDER|AIOPS_LLM_MODEL|AIOPS_LLM_API_KEY|AIOPS_LLM_BASE_URL|AIOPS_LLM_COMPACT_MODEL|AIOPS_LLM_FALLBACK_PROVIDER|AIOPS_LLM_FALLBACK_MODEL|AIOPS_LLM_FALLBACK_API_KEY|AIOPS_LLM_CONFIG_FILE|AIOPS_GRPC_AUTO_PORT|AIOPS_GRPC_FALLBACK_ADDR|AIOPS_MYSQL_DSN|AIOPS_AUTH_OAUTH_AUTHORIZE_URL|AIOPS_AUTH_OAUTH_EMAIL|AIOPS_AUTH_OAUTH_PLAN_TYPE|AIOPS_ACTION_TOKEN_SECRET|AIOPS_OTEL_ENDPOINT|AIOPS_OTEL_SERVICE_NAME|AIOPS_OTEL_PROJECT|AIOPS_OTEL_ENABLED|AIOPS_AGENT_SERVER_URL|AIOPS_AGENT_GRPC_URL|AIOPS_API_URL|AIOPS_REPO_ROOT|SSH_AUTH_SOCK|AIOPS_DEBUG_MODEL_INPUT_TRACE|AIOPS_DEBUG_FINAL_STATE|AIOPS_DEBUG_TRANSPORT_PROJECTION|AIOPS_DEBUG_TRANSCRIPT_PROJECTION|AIOPS_WORKFLOW_REFERENCE_GUARD_MODE|AIOPS_OPS_MANUAL_AUTO_RETRIEVAL|AIOPS_WORKFLOW_VALIDATION_PROVIDER|AIOPS_WORKFLOW_VALIDATION_IMAGE|AIOPS_INTENT_FRAME_ROUTING|AIOPS_FLAG_READONLY_TOOL_RETRY|AIOPS_READONLY_TOOL_RETRY'

targets=(
  cmd
  internal
  web
  docker
  scripts
  deploy
  README.md
  docs
)

if rg -n "$forbidden" "${targets[@]}" \
  --glob '!scripts/check-runtime-env-allowlist.sh' \
  --glob '!docs/archive/**' \
  --glob '!docs/superpowers/**' \
  --glob '!docs/20*.md'; then
  echo "Forbidden runtime env names found. Move runtime behavior to DB-backed Runtime Settings or a dedicated config page." >&2
  exit 1
fi

echo "runtime env allowlist check passed"
