#!/usr/bin/env bash
set -euo pipefail

export AIOPS_HTTP_ADDR="${AIOPS_HTTP_ADDR:-127.0.0.1:18083}"
export AIOPS_GRPC_ADDR="${AIOPS_GRPC_ADDR:-127.0.0.1:18093}"
export AIOPS_DEBUG_MODEL_INPUT_TRACE="${AIOPS_DEBUG_MODEL_INPUT_TRACE:-1}"
export AIOPS_DEBUG_MODEL_INPUT_TRACE_DIR="${AIOPS_DEBUG_MODEL_INPUT_TRACE_DIR:-.data/model-input-traces}"
export AIOPS_DEBUG_FINAL_STATE="${AIOPS_DEBUG_FINAL_STATE:-1}"
export AIOPS_DEBUG_TRANSPORT_PROJECTION="${AIOPS_DEBUG_TRANSPORT_PROJECTION:-1}"
export AIOPS_RUNNER_DISABLED="${AIOPS_RUNNER_DISABLED:-1}"

exec .data/bin/ai-server
